apiVersion: v1
kind: Service
metadata:
  name: httpserver-service
spec:
  #type: LoadBalancer
  type: ClusterIP
  selector:
    app: httpserver
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 80
