apiVersion: v1
kind: Service
metadata:
  name: httpserver-service
spec:
  #  type: ClusterIP
  type: LoadBalancer
  externalIPs:
    - 192.168.34.11
  selector:
    app: httpserver
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 80
